# Generated by Django 5.1.7 on 2025-04-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_callrequest_recording_url_callrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrequest',
            name='transcription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
